Feat/crawling
civilian38/review-based-recommendation pull request #3
Opened 2024-05-06 10:58 UTC by CurlyKkoma

잘 돌아가는지 테스트 해보고 리뷰 남겨주세요

2024-05-07 04:25 UTC, civilian38 requested changes
코멘트 확인해주세요!

2024-05-07 04:25 UTC, civilian38 commented on crawling/crawling_module.py
> +#parser.add_argument('--professor', required=True)
professor를 parameter로 받지 않는 이유가 있나요? '컴퓨터프로그래밍'으로 검색했을 때 이영기 교수님 강의만 불러오고 엄현상 교수님 강의는 불러오지 않아서... professor도 포함해서 크롤링 해야할 것 같습니다

2024-05-07 04:25 UTC, civilian38 commented on crawling/crawling_module.py
> +# Selenium 4.6부터 사용 가능
가상환경에서 새로운 패키지 설치할 때마다 터미널에서 'pip freeze > requirements.txt' 입력하면 다른 환경에서도 같은 버전의 패키지를 공유할 수 있습니다.

https://computer-science-student.tistory.com/221
이거 참고해 주세요!

2024-05-07 04:25 UTC, civilian38 commented on crawling/crawling_module.py
> +#parser.add_argument('--professor', required=True)
이영기 교수님 강의평만 봤을때 크롤링은 잘 작동하는것 같습니다. 다만 별점을 안갖고 오는건 의도된건가요?

2024-05-07 04:53 UTC, CurlyKkoma commented on crawling/crawling_module.py
> +#parser.add_argument('--professor', required=True)
쓰기 모드를 append가 아니라 write로 해서 마지막 교수님 강의만 덮어씌워졌네요...
별점은 강의평 임베딩할 때 필요 없을 것 같다고 생각해 안 가져왔는데, 별점도 가져오도록 수정해서 다시 올리겠습니다.

2024-05-08 07:12 UTC, CurlyKkoma commented
수정 다시 해서 올렸습니다. cp949로 하니 오류나는 강의평이 있어서 utf-8로 인코딩 바꿨고, 엑셀 대신 파이참에서 데이터 확인하면 안 깨지고 보일겁니다. 테스트하고 리뷰 남겨주세요

2024-05-08 10:12 UTC, civilian38 commented
인코딩이 utf-8로 설정되지 않은 것 같아서 제가 변경했습니다. 기능은 정상 작동하네요!
가끔 교수님 이름이 Not determined가 뜨는데 아직 원인을 찾아보진 않아서.. 일단 머지시켜놓고 나중에 해결해보겠습니다.

2024-05-08 10:13 UTC, civilian38 approved these changes

2024-05-08 10:13 UTC, merged