Feat/crawling by file
civilian38/review-based-recommendation pull request #6
Opened 2024-05-11 07:26 UTC by CurlyKkoma

파일 읽어서 크롤링 하는 crawling_by_file.py를 만들었습니다. 
실행은 crawling module과 비슷하게 

python crawling/crawling_by_file.py --id [id] --pw [pw] --i [파싱 파일 제목 (.csv 없이)] --out [저장할 파일 제목 (.csv 없이)]

입니다.

2024-05-11 09:56 UTC, civilian38 requested changes
![github error](https://github.com/civilian38/review-based-recommendation/assets/70161936/4fd900d0-96a1-43a1-bf97-3726d48d22a8)
코멘트에 언급한 몇가지를 수정했을 때 전반적으로 잘 작동했지만, 문제가 있었습니다.
CSV 파일의 첫 4개 강의만 남기고 나머지는 지운 채로 테스트를 진행해봤는데, "대학 글쓰기 2: 사회과학글쓰기" 강의를 크롤링 하면서 다음과 같은 에러가 발생했습니다.

`DevTools listening on ws://127.0.0.1:64034/devtools/browser/f13e7eb6-1337-452e-ae39-d3ac5b514d6b
Traceback (most recent call last):
  File "C:\Users\gyk23\OneDrive\문서\github\review-based-recommendation\crawling\crawling_module.py", line 52, in <module>
    id_input = WebDriverWait(driver, 10).until(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gyk23\OneDrive\문서\github\review-based-recommendation\.venv\Lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
        GetHandleVerifier [0x00007FF6C5F61562+60802]
        (No symbol) [0x00007FF6C5EDAC62]
        (No symbol) [0x00007FF6C5D97CE4]
        (No symbol) [0x00007FF6C5DE6D4D]
        (No symbol) [0x00007FF6C5DE6E1C]
        (No symbol) [0x00007FF6C5E2CE37]
        (No symbol) [0x00007FF6C5E0ABBF]
        (No symbol) [0x00007FF6C5E2A224]
        (No symbol) [0x00007FF6C5E0A923]
        (No symbol) [0x00007FF6C5DD8FEC]
        (No symbol) [0x00007FF6C5DD9C21]
        GetHandleVerifier [0x00007FF6C62641FD+3217949]
        GetHandleVerifier [0x00007FF6C62A6197+3488183]
        GetHandleVerifier [0x00007FF6C629F11F+3459391]
        GetHandleVerifier [0x00007FF6C601B926+823622]
        (No symbol) [0x00007FF6C5EE5FFF]
        (No symbol) [0x00007FF6C5EE0F24]
        (No symbol) [0x00007FF6C5EE10B2]
        (No symbol) [0x00007FF6C5ED1904]
        BaseThreadInitThunk [0x00007FFE0A62257D+29]
        RtlUserThreadStart [0x00007FFE0B08AA48+40]
`

원인을 찾아보진 않았는데... 짐작 가시는게 있나요?

2024-05-11 09:56 UTC, civilian38 commented on crawling/crawling_by_file.py
> +    os.system('python crawling/crawling_module.py --id {} --pw {} --subject \'{}\' --out {}'.format(id,pw,subject,out_file))
제 환경에서는 --subject \'{}\' 로는 동작하지 않고 --subject "{}"로 작성해야 동작하는데, 맥에서는 다른가요?

2024-05-11 09:56 UTC, civilian38 commented on crawling/crawling_by_file.py
> +with open(in_file,'r') as f:
parameter에 encoding='utf-8'도 추가해야될 것 같습니다. 제 환경에서는 인코딩을 cp949로 하네요. 버전이나 운영체제 문제로 생각되긴 합니다

2024-05-11 09:56 UTC, civilian38 commented on crawling/crawling_by_file.py
> +#python crawling/crawling_by_file.py --id [id] --pw [pw] --i [강의명 목록 저장된 파일 이름] --out [내보낼 파일 이름]
이렇게되면 파일 하나에 모든 강의평을 담게 되는데, 강의명별로 파일을 따로 만들기로 하지 않았나요...?

2024-05-12 03:58 UTC, CurlyKkoma commented on crawling/crawling_by_file.py
> +#python crawling/crawling_by_file.py --id [id] --pw [pw] --i [강의명 목록 저장된 파일 이름] --out [내보낼 파일 이름]
위의 문제들은 다 운영체제 차이인 것 같습니다. 강의평 별로 파일 만들기는 제가 깜빡했네요. 대글2 사회과학글쓰기는 한 번 확인해보겠습니다.

2024-05-12 04:25 UTC, CurlyKkoma commented
@civilian38 @SeungChanBaek-stat 
위의 내용들 수정해서 다시 커밋했습니다. 사회과학글쓰기 에러는 제가 돌렸을 때는 안 일어나는데, 타임아웃 에러인 것으로 봐서 아마 인터넷 문제였지 않을까 싶어요.

2024-05-15 02:31 UTC, civilian38 approved these changes

2024-05-15 02:31 UTC, merged